language: ruby
rvm:
  - 1.9.3
before_script:
after_script:
script: "bundle exec rake spec"
env:
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.7.3
notifications:
  email: false
branches:
  only:
    - master
    - dev
